### PR TITLE
Updated storybook/gh-pages

### PR DESCRIPTION
**Pull request by ezralalonde**
Project storybook changed: update the public site.

### CODE REVIEW

**Comment by ezralalonde** [comment]
I just ran `build-storybook` and updated the `gh-pages` branch with the results.

See https://ezralalonde.github.io/material-ui-chip-input/

**Comment by leMaik** [comment]
Actually, you just need to run `npm run deploy-storybook` and then the script will handle all of this. :) I'll redeploy the pages, thanks for the reminder. :+1:

**Comment by ezralalonde** [comment]
`npm run deploy-storybook` was doing weird things to my branch. It wouldn't let me submit a pull request.

Anyway, I'm glad it's taken care of.

**Comment by leMaik** [comment]
Maybe it doesn't work in a branch that is not pushed? :thinking:

**Comment by ezralalonde** [comment]
I'd pushed my local copy. I forget the exact details, but I ended up deleting the branch and trying again, with the above result as the PR.

It was definitely in those rare, and weird git issues that you can spend hours trying to understand and deal with "properly" I only wanted to spend a few seconds so I used the biggest, dumb hammer I could find: `git reset --hard`, reapplying the patch, then force-pushing. It doesn't really matter either way. The storybook is updated, and that's good enough for me.

Thanks again!

**Pull request closed without merging**
