### PR TITLE
focusing to the last inputted chip when left arrow is triggered and …

### PR DESCRIPTION
**Pull request by muhilham**
fix undefined focusedChip value when right and left arrow is triggered

### CODE REVIEW

**Comment by muhilham** [comment]
ISSUE #151

**Comment by leMaik** [comment]
Nice! :+1: Thanks a lot.

**Comment by muhilham** [comment]
My pleasure, dude. What version will this changes applied and when will you release it ?

**Comment by leMaik** [comment]
Soon. :+1: There are still some regressions from v0.18.0 that I'd like to fix in the next release.

**Pull request merged**
