### PR TITLE
fix undefined `length` error & console error when `onBeforeRequestAdd` is on

### PR DESCRIPTION
**Pull request by tjandraflorence**
- fix undefined `length` of `inputValue`
- fix console error for `onBeforeRequestAdd`

### CODE REVIEW

**Comment by tjandraflorence** [comment]
#153

**Comment by leMaik** [comment]
Thank you very much! :+1:

**Comment by jriuamb** [comment]
Thanks allot for solve this bug!
Another thing. When onBeforeRequestAdd returns false, I need that not clear input

**Comment by leMaik** [comment]
@jriuamb Would you mind opening a new issue?

**Comment by jriuamb** [comment]
Ok :+1:

**Pull request merged**
